### ISSUE TITLE
How to run the Icon Browser?

### ISSUE THREAD

**Issue by JLTook11** [MahApps/MahApps.Metro.IconPacks.Browser#1]
Sorry if this is just me... but how do I run the browser?   I can clone the repository, but nothing to run...

Must be missing something obvious  :(  

Thanks in advance!

**Comment by Pardoe** [comment]
Same question as JLTool11

**Comment by punker76** [comment]
This repo is currently a placeholder for the next versions of the IconPacks Browser.

If it's not necessary to look in to the code then you can download the browser at the [release page](https://github.com/MahApps/MahApps.Metro.IconPacks/releases) of the main repo. Otherwise you can clone the [main repo](https://github.com/MahApps/MahApps.Metro.IconPacks) and select the `MahApps.Metro.IconPacks.Browser` project as the startup project via context menu:

![image](https://user-images.githubusercontent.com/658431/116824960-1f5f2680-ab8d-11eb-91e4-1b6f55696144.png)

**Comment by roboticsware** [comment]
There is no binary of the iconpack browser in the release page you mentioned.

**Comment by M-Saadawy** [comment]
> There is no binary of the iconpack browser in the release page you mentioned.

Same here!

**Comment by punker76** [comment]
New place for the browser is: https://github.com/MahApps/IconPacks.Browser/releases
